env:
  global:
    - CC_TEST_REPORTER_ID=1e505389057690635b666df438a65ffdd06ea0cef4caeacba4e5a073ef974bea
    
language: java

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
